name: Deploy
on:
  push:
    branches:
      - master

jobs:
  FirestoreHostingDeploy:
    name: FirestoreHostingDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install
          npm install -g firebase-tools

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
